### ISSUE TITLE
Change IMG_CACHE_SIZE to eliminate flicker/lines

### ISSUE THREAD

**Issue by carlfugate** [koriwi/freedeck-ino#12]
Current IMG_CACHE_SIZE of 512 causes display issues.  As recommended by Adam Welch, it seems that 128 is the most stable and immediately fixed my problems.

**Comment by koriwi** [comment]
Yeah, maybe we should change the default value. If you have higher quality screens, they are faster and can work with higher values

**Comment by carlfugate** [comment]
Maybe it would just be better then to leave a comment in that section that you should try the different values based on your screen.

**Comment by koriwi** [comment]
done
